# Generated by Django 4.2.4 on 2023-08-12 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='worker',
            old_name='second_name',
            new_name='last_name',
        ),
    ]
