# Generated by Django 4.2.4 on 2023-08-12 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0002_rename_second_name_worker_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantsmodel',
            name='plants_name',
            field=models.CharField(default='Enter plant name', max_length=100),
        ),
    ]
